version: '3.3'

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-itau
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: redis-itau
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql-data:
  redis_data: